CFLAGS = -O2 -Wall -Wextra -std=c11
TARGETS = array_max_part1 prefix_sum_part2

all: $(TARGETS)

array_max_part1: include/array_max_part1.c include/timing.h
	$(CC) $(CFLAGS) $< -o $@

prefix_sum_part2: include/prefix_sum_part2.c include/timing.h
	$(CC) $(CFLAGS) $< -o $@

clean:
	rm -f $(TARGETS)
.PHONY: all clean
